### ISSUE TITLE
Laravel 5,0

### ISSUE THREAD

**Issue by mrakodol** [bllim/laravel4-datatables-package#165]
Hi,
Laravel 5,0 is soon coming out, can you update this nice package to work with new laravel 5?

**Comment by jgarciac** [comment]
+1

**Comment by MarkVaughn** [comment]
As there are a lot of open bugs and not enough contributors I suggest we
fork this project for the laravel 5 release that only supports the newest
datatables ( have the laravel 4 version support the old datatables.)

Mark Vaughn
Mobile: +1 (770) 533-2274

**Comment by abada** [comment]
+1

**Comment by multiarts** [comment]
+1

**Comment by MarkVaughn** [comment]
https://github.com/bllim/laravel4-datatables-package/releases/tag/v1.5.0-alpha
