### ISSUE TITLE
setRowClass only allows one class

### ISSUE THREAD

**Issue by grandehombre** [bllim/laravel4-datatables-package#207]
Hi,

I have the following code
```php
		return Datatables::of($entityObjects)
			->set_row_class('@if($deleted_at != "") deletedRow @endif')
			->set_row_class('@if($is_dummy_user == true) dummyUserRow @endif')
			->make();
```
where I want to add the class 'deletedRow' and/or 'dummyUser' to a row.
The current version of this package only handles one class.

I have modified DataTables.php as follows, in order to allow multiple classes.

```php

// line 56
//was     protected $row_class_tmpl = null;
    protected $row_class_tmpl = '';

// line 321 
public function setRowClass($content)
    {
        // was $this->row_class_tmpl = $content;
        $this->row_class_tmpl .= ' '.$content;

        return $this;
    }
```

**Comment by MarkVaughn** [comment]
as I am not sure what you are doing  why didn't you do this:
```` -
->set_row_class('@if($deleted_at != "") deletedRow @endif @if($is_dummy_user == true) dummyUserRow @endif')
````

as set_XXX usually set's value, not appends things. your change might break other peoples code

**Comment by grandehombre** [comment]
Thanks Mark!
Sometimes it seems that the brain switches off and just watches to see what we do.
In this case, I obliged it by acting like I only started programming yesterday. Ahem....

Thanks again, I restored the code back to its original state and have implemented as above.
