### ISSUE TITLE
Left Join Not Work

### ISSUE THREAD

**Issue by githubhasib** [bllim/laravel4-datatables-package#214]
I am trying to left join in my query but it shows error Not unique table\/alias: 'users'

      $result = DB::table('reports')
            ->select('reports.id as id', 'users.facebookname as username','users.facebookname as reporteduser','reports.text as message')
            ->leftJoin('users', 'users.id', '=', 'orders.user_id')
            ->leftJoin('users', 'users.id', '=', 'orders.reported_user_id');
        return Datatables::of($result)

            ->add_column('delete', '<a href="/admin/reports/destroy/{{ $id }}"><i class="icon-trash"></i>Delete</a>')
            ->make();

**Comment by MarkVaughn** [comment]
This has nothing to do with datatables, but here's the solution to your SQL error
  ```
$result = DB::table('reports')
        ->select('reports.id as id', 'users.facebookname as username','reported_user.facebookname as reporteduser','reports.text as message')
        ->leftJoin('users', 'users.id', '=', 'orders.user_id')
        ->leftJoin('users AS reported_user', 'users.id', '=', 'orders.reported_user_id');
    return Datatables::of($result)

        ->add_column('delete', '<a href="/admin/reports/destroy/{{ $id }}"><i class="icon-trash"></i>Delete</a>')
        ->make();
```
